# Generated by Django 2.0.5 on 2019-12-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20191228_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='mac_address',
            field=models.CharField(db_index=True, help_text='MAC地址', max_length=30, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='name',
            field=models.CharField(db_index=True, help_text='网卡设备名', max_length=20, verbose_name='网卡设备名'),
        ),
    ]
