# Generated by Django 2.0.5 on 2019-12-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20191228_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'permissions': {('view_server', 'can view server')}},
        ),
    ]
