# Generated by Django 2.0.5 on 2020-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20191231_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.IntegerField(db_index=True, default=0, help_text='机器类型', verbose_name='机器类型'),
        ),
    ]
